import { chromium } from 'playwright';
const b=await chromium.launch();
const c=await b.newContext({viewport:{width:1440,height:900}});
const p=await c.newPage();
await p.goto('http://127.0.0.1:3001/agents',{waitUntil:'networkidle'});
await p.waitForTimeout(1500);
await p.getByRole('button',{name:/new coworker|add a coworker/i}).first().click();
await p.waitForTimeout(1500);
const f=p.locator('input, textarea');
await f.nth(0).fill('Sage');
await f.nth(1).fill('Product Analyst');
await f.nth(2).fill('Turns product questions into evidence-backed answers.');
await f.nth(3).fill('Ask for the metric before the opinion. Say what you do not know.');
await p.waitForTimeout(400);
await p.getByRole('button',{name:/create/i}).last().click();
await p.waitForTimeout(11000);
console.log('URL='+p.url());
console.log('IS404='+/(doesn.t exist|unavailable|404)/i.test(await p.locator('body').innerText()));
const i=p.locator('textarea, [contenteditable=true]').first();
await i.waitFor({timeout:20000});
await i.fill('Use workspace_write to save notes/claude-proof.md with the single line "claude engine live". Then read it back and quote it.');
await i.press('Enter');
await p.waitForTimeout(90000);
const t=await p.locator('body').innerText();
console.log('TAIL='+t.slice(-300).replace(/\s+/g,' '));
await b.close();