import { chromium } from 'playwright';
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1440,height:900}});
await p.goto('http://127.0.0.1:3001/conversations/317f37e8-f628-4198-b51b-0b50ff399c20',{waitUntil:'networkidle'});
await p.waitForTimeout(2000);
const MSG='Please save a short note to your own workspace using the workspace_write tool. Path: notes/workspace-boundary.md  Content: a one-paragraph markdown note saying that agent persistent files are managed by ContextFS, and the provider local working directory is not the same as Files. After writing, call workspace_read on that path and tell me exactly what you read back.';
const box=p.locator('textarea, [contenteditable=true]').first();
await box.click(); await box.fill(MSG); await p.waitForTimeout(300);
await p.keyboard.press('Enter');
console.log('sent, waiting for tool calls...');
await p.waitForTimeout(90000);
await p.screenshot({path:'/tmp/overify/09-tool-reply.png',fullPage:false});
const t=(await p.locator('body').innerText()).replace(/\s+/g,' ');
const i=t.indexOf('workspace-boundary');
console.log(i>0 ? t.slice(Math.max(0,i-400), i+500) : t.slice(-600));
await b.close();
