export const realPostgresSuites = [
  'tests/integration/real-pg-pool.integration.test.ts',
  'tests/integration/postgres-migration-concurrency.integration.test.ts',
  'tests/integration/agent-registry-postgres.integration.test.ts',
  'tests/integration/session-lane-postgres.integration.test.ts',
  'tests/integration/runtime-memory-real-pg.integration.test.ts',
  'tests/integration/run-cancellation-postgres.integration.test.ts',
  'tests/integration/lark-memory-card-doc-real-pg.integration.test.ts',
  'tests/integration/postgres-run-event-concurrency.integration.test.ts',
  'tests/integration/product-api-v1-oi38.integration.test.ts',
  'tests/integration/work-composition-real-pg.integration.test.ts',
  'tests/integration/product-work-definition-real-pg.integration.test.ts',
  'tests/integration/product-work-list-order-real-pg.integration.test.ts',
  'tests/integration/team-attempt-terminal-race.integration.test.ts',
  'tests/integration/managed-single-agent-faults.integration.test.ts',
] as const satisfies readonly string[];
